<?php

namespace App\Command;

use App\Entity\SitePage;
use App\Entity\SitePageTranslation;
use App\Repository\SitePageRepository;
use App\Service\I18n\AiTranslationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:i18n:translate',
    description: 'Generate controlled AI translations for localized content without publishing them.',
)]
final class I18nTranslateCommand extends Command
{
    public function __construct(
        private readonly SitePageRepository $sitePageRepository,
        private readonly AiTranslationService $translationService,
        private readonly EntityManagerInterface $entityManager,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('locale', null, InputOption::VALUE_REQUIRED, 'Target locale: en or es.')
            ->addOption('entity', null, InputOption::VALUE_REQUIRED, 'Entity type. Initial executable support: SitePage.', 'SitePage')
            ->addOption('id', null, InputOption::VALUE_REQUIRED, 'Filter by entity id.')
            ->addOption('slug', null, InputOption::VALUE_REQUIRED, 'Filter by source FR slug.')
            ->addOption('status', null, InputOption::VALUE_REQUIRED, 'Filter by existing target translation status.')
            ->addOption('only-missing', null, InputOption::VALUE_NONE, 'Only generate missing translations.')
            ->addOption('only-outdated', null, InputOption::VALUE_NONE, 'Only regenerate outdated translations.')
            ->addOption('overwrite', null, InputOption::VALUE_NONE, 'Overwrite existing translations. Output status remains ai_translated.')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Plan work without calling AI or persisting.')
            ->addOption('limit', null, InputOption::VALUE_REQUIRED, 'Maximum number of rows to process.', '10');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $locale = (string) $input->getOption('locale');
        $entity = (string) $input->getOption('entity');
        $dryRun = (bool) $input->getOption('dry-run');
        $overwrite = (bool) $input->getOption('overwrite');
        $onlyMissing = (bool) $input->getOption('only-missing');
        $onlyOutdated = (bool) $input->getOption('only-outdated');
        $limit = max(1, (int) $input->getOption('limit'));

        if (!in_array($locale, [SitePageTranslation::LOCALE_EN, SitePageTranslation::LOCALE_ES], true)) {
            $io->error('Use --locale=en or --locale=es.');
            return Command::FAILURE;
        }

        if ($entity !== 'SitePage') {
            $io->warning('Executable AI translation currently supports SitePage. Other translation-backed entities are registered for the workflow but not batch-generated by this command yet.');
            return Command::FAILURE;
        }

        $pages = $this->selectSitePages($input, $limit);
        $rows = [];
        $counts = ['generated' => 0, 'skipped' => 0, 'conflict' => 0, 'error' => 0];

        foreach ($pages as $page) {
            $plan = $this->translationService->planSitePage($page, $locale, $overwrite, $onlyMissing, $onlyOutdated);
            if ($input->getOption('status') && $plan['currentStatus'] !== $input->getOption('status')) {
                continue;
            }

            $rows[] = [
                $plan['entity'],
                (string) ($plan['id'] ?? ''),
                (string) ($plan['slug'] ?? ''),
                $plan['locale'],
                implode(',', $plan['fields']),
                $plan['currentStatus'] ?? 'missing',
                $plan['outdated'] ? 'yes' : 'no',
                $plan['action'],
            ];

            if ($dryRun || str_starts_with($plan['action'], 'skip')) {
                ++$counts['skipped'];
                continue;
            }

            try {
                $this->translationService->translateSitePage($page, $locale, $overwrite, $onlyMissing, $onlyOutdated);
                ++$counts['generated'];
            } catch (\App\Service\I18n\AiTranslationConflictException $exception) {
                ++$counts['conflict'];
                $io->warning($exception->getMessage());
            } catch (\Throwable $exception) {
                ++$counts['error'];
                $io->error($exception->getMessage());
            }
        }

        $io->table(['source', 'id', 'slug', 'target', 'fields', 'current status', 'outdated', 'action'], $rows);
        if (!$dryRun) {
            $this->entityManager->flush();
        }
        $io->success(sprintf(
            'rows=%d generated=%d skipped=%d conflict=%d error=%d dry_run=%s',
            count($rows),
            $counts['generated'],
            $counts['skipped'],
            $counts['conflict'],
            $counts['error'],
            $dryRun ? 'yes' : 'no'
        ));

        return ($counts['conflict'] > 0 || $counts['error'] > 0) ? Command::FAILURE : Command::SUCCESS;
    }

    /**
     * @return SitePage[]
     */
    private function selectSitePages(InputInterface $input, int $limit): array
    {
        if ($input->getOption('id')) {
            $page = $this->sitePageRepository->find((int) $input->getOption('id'));
            return $page instanceof SitePage ? [$page] : [];
        }

        if ($input->getOption('slug')) {
            $page = $this->sitePageRepository->findOneBy(['slug' => (string) $input->getOption('slug')]);
            return $page instanceof SitePage ? [$page] : [];
        }

        return $this->sitePageRepository->findBy([], ['slug' => 'ASC'], $limit);
    }
}
