<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add FR translation tables for structured public content';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE practice_translation (id INT AUTO_INCREMENT NOT NULL, practice_id INT NOT NULL, locale VARCHAR(5) NOT NULL, designation VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, designation_short VARCHAR(255) DEFAULT NULL, h1_title VARCHAR(255) DEFAULT NULL, introduction LONGTEXT DEFAULT NULL, introduction_short LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, description_short LONGTEXT DEFAULT NULL, tags JSON DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_practice_translation_locale (practice_id, locale), UNIQUE INDEX uniq_practice_translation_locale_slug (locale, slug), INDEX IDX_4EEBC526520282E8 (practice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_translation (id INT AUTO_INCREMENT NOT NULL, service_id INT NOT NULL, locale VARCHAR(5) NOT NULL, designation VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, designation_short VARCHAR(255) DEFAULT NULL, introduction_short LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, description_short LONGTEXT DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_service_translation_locale (service_id, locale), UNIQUE INDEX uniq_service_translation_locale_slug (locale, slug), INDEX IDX_21CC5B9FED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet_translation (id INT AUTO_INCREMENT NOT NULL, projet_id INT NOT NULL, locale VARCHAR(5) NOT NULL, designation VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, short_description LONGTEXT DEFAULT NULL, client_name VARCHAR(255) DEFAULT NULL, territory VARCHAR(255) DEFAULT NULL, period_label VARCHAR(255) DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_projet_translation_locale (projet_id, locale), UNIQUE INDEX uniq_projet_translation_locale_slug (locale, slug), INDEX IDX_68C494CDC18272 (projet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_translation (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, locale VARCHAR(5) NOT NULL, titre VARCHAR(255) DEFAULT NULL, shortcv LONGTEXT DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_team_translation_locale (team_id, locale), INDEX IDX_C6D979FE296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE legal_page_translation (id INT AUTO_INCREMENT NOT NULL, legal_page_id INT NOT NULL, locale VARCHAR(5) NOT NULL, slug VARCHAR(190) NOT NULL, title VARCHAR(255) DEFAULT NULL, body LONGTEXT DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_legal_page_translation_locale (legal_page_id, locale), UNIQUE INDEX uniq_legal_page_translation_locale_slug (locale, slug), INDEX IDX_3C3C9E8119BDEE49 (legal_page_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE home_section_translation (id INT AUTO_INCREMENT NOT NULL, home_section_id INT NOT NULL, locale VARCHAR(5) NOT NULL, slug VARCHAR(190) NOT NULL, title VARCHAR(255) DEFAULT NULL, eyebrow VARCHAR(255) DEFAULT NULL, intro LONGTEXT DEFAULT NULL, cta_label VARCHAR(255) DEFAULT NULL, cta_label_secondary VARCHAR(255) DEFAULT NULL, translation_status VARCHAR(32) NOT NULL, source_content_hash VARCHAR(64) DEFAULT NULL, source_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_home_section_translation_locale (home_section_id, locale), UNIQUE INDEX uniq_home_section_translation_locale_slug (locale, slug), INDEX IDX_7D8E0219CF118530 (home_section_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE practice_translation ADD CONSTRAINT FK_4EEBC526520282E8 FOREIGN KEY (practice_id) REFERENCES practice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_translation ADD CONSTRAINT FK_21CC5B9FED5CA9E6 FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet_translation ADD CONSTRAINT FK_68C494CDC18272 FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_translation ADD CONSTRAINT FK_C6D979FE296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE legal_page_translation ADD CONSTRAINT FK_3C3C9E8119BDEE49 FOREIGN KEY (legal_page_id) REFERENCES legal_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE home_section_translation ADD CONSTRAINT FK_7D8E0219CF118530 FOREIGN KEY (home_section_id) REFERENCES home_section (id) ON DELETE CASCADE');

        $this->addSql("INSERT INTO practice_translation (practice_id, locale, designation, slug, designation_short, h1_title, introduction, introduction_short, description, description_short, tags, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', designation, slug, designation_short, h1_title, introduction, introduction_short, description, description_short, tags, 'published', SHA2(CONCAT_WS('|', designation, slug, COALESCE(designation_short, ''), COALESCE(h1_title, ''), COALESCE(introduction, ''), COALESCE(introduction_short, ''), COALESCE(description, ''), COALESCE(description_short, ''), COALESCE(JSON_EXTRACT(tags, '$'), '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM practice");
        $this->addSql("INSERT INTO service_translation (service_id, locale, designation, slug, designation_short, introduction_short, description, description_short, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', designation, slug, designation_short, introduction_short, description, description_short, 'published', SHA2(CONCAT_WS('|', designation, COALESCE(slug, ''), COALESCE(designation_short, ''), COALESCE(introduction_short, ''), COALESCE(description, ''), COALESCE(description_short, '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM services");
        $this->addSql("INSERT INTO projet_translation (projet_id, locale, designation, slug, description, short_description, client_name, territory, period_label, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', designation, slug, description, short_description, client_name, territory, period_label, 'published', SHA2(CONCAT_WS('|', designation, slug, COALESCE(description, ''), COALESCE(short_description, ''), COALESCE(client_name, ''), COALESCE(territory, ''), COALESCE(period_label, '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM projet");
        $this->addSql("INSERT INTO team_translation (team_id, locale, titre, shortcv, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', titre, shortcv, 'published', SHA2(CONCAT_WS('|', COALESCE(titre, ''), COALESCE(shortcv, '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM team");
        $this->addSql("INSERT INTO legal_page_translation (legal_page_id, locale, slug, title, body, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', slug, title, body, 'published', SHA2(CONCAT_WS('|', slug, COALESCE(title, ''), COALESCE(body, '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM legal_page");
        $this->addSql("INSERT INTO home_section_translation (home_section_id, locale, slug, title, eyebrow, intro, cta_label, cta_label_secondary, translation_status, source_content_hash, source_updated_at, created_at, updated_at) SELECT id, 'fr', slug, title, eyebrow, intro, cta_label, cta_label_secondary, 'published', SHA2(CONCAT_WS('|', slug, COALESCE(title, ''), COALESCE(eyebrow, ''), COALESCE(intro, ''), COALESCE(cta_label, ''), COALESCE(cta_label_secondary, '')), 256), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM home_section");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE home_section_translation DROP FOREIGN KEY FK_7D8E0219CF118530');
        $this->addSql('ALTER TABLE legal_page_translation DROP FOREIGN KEY FK_3C3C9E8119BDEE49');
        $this->addSql('ALTER TABLE team_translation DROP FOREIGN KEY FK_C6D979FE296CD8AE');
        $this->addSql('ALTER TABLE projet_translation DROP FOREIGN KEY FK_68C494CDC18272');
        $this->addSql('ALTER TABLE service_translation DROP FOREIGN KEY FK_21CC5B9FED5CA9E6');
        $this->addSql('ALTER TABLE practice_translation DROP FOREIGN KEY FK_4EEBC526520282E8');
        $this->addSql('DROP TABLE home_section_translation');
        $this->addSql('DROP TABLE legal_page_translation');
        $this->addSql('DROP TABLE team_translation');
        $this->addSql('DROP TABLE projet_translation');
        $this->addSql('DROP TABLE service_translation');
        $this->addSql('DROP TABLE practice_translation');
    }
}
