<?php

return [
    [
        'name' => 'Sage X3',
        'slug' => 'sage-x3',
        'aliases' => ['Sage X3', 'X3', 'Sage Enterprise Management'],
        'editor' => 'Sage',
        'family' => 'ERP / Finance',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Sage X3 lorsque la mission associée est documentée.',
        'target_pages' => ['/business-apps/erp', '/si-finance', '/facturation-electronique-amoa'],
        'guardrails' => 'Utiliser Sage X3 comme nom canonique. Ne pas écrire « Cegid X3 ».',
    ],
    [
        'name' => 'Divalto Infinity',
        'slug' => 'divalto-infinity',
        'aliases' => ['Divalto Infinity', 'Divalto'],
        'editor' => 'Divalto',
        'family' => 'ERP / Gestion commerciale',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Divalto Infinity lorsque la mission associée est documentée.',
        'target_pages' => ['/business-apps/erp'],
        'guardrails' => 'Forte preuve opérationnelle : feuille de route, tests, développements, habilitations.',
    ],
    [
        'name' => 'MAPSI',
        'slug' => 'mapsi',
        'aliases' => ['MAPSI', 'Mapsi'],
        'editor' => 'OLING',
        'family' => 'GRC / RGPD / QSE / PCA',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant MAPSI lorsque la mission associée est documentée.',
        'target_pages' => ['https://mapsi.fr/fr/logiciel-grc', '/expertises-audit/rgpd', '/expertises-audit/qse'],
        'guardrails' => 'Produit OLING : possibilité de formulation plus directe que pour les logiciels tiers.',
    ],
    [
        'name' => 'PEP Premium',
        'slug' => 'pep-premium',
        'aliases' => ['PEP Premium', 'PEP', 'SIFI PEP'],
        'editor' => 'Nexpublica',
        'family' => 'SI Finance / GBCP',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui après validation client',
        'wording' => 'OLING intervient sur des projets impliquant PEP Premium lorsque la mission associée est documentée.',
        'target_pages' => ['/si-finance', '/amoa-si'],
        'guardrails' => 'Code projet Dolibarr à rattacher. Ne pas inventer un code.',
    ],
    [
        'name' => 'Microsoft Power BI',
        'slug' => 'microsoft-power-bi',
        'aliases' => ['Power BI', 'Microsoft Power BI', 'Power BI Service'],
        'editor' => 'Microsoft',
        'family' => 'BI / Data / Reporting',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Microsoft Power BI lorsque la mission associée est documentée.',
        'target_pages' => ['/amoa-si', '/projets'],
        'guardrails' => 'Ne pas prétendre être partenaire Microsoft sauf preuve distincte.',
    ],
    [
        'name' => 'Advantage Finance / SIGMA',
        'slug' => 'advantage-finance-sigma',
        'aliases' => ['Advantage Finance', 'SIGMA', 'SIGMA Finance', 'SIGMA Budget'],
        'editor' => 'À confirmer',
        'family' => 'ERP Finance / Budget',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Advantage Finance / SIGMA lorsque la mission associée est documentée.',
        'target_pages' => ['/si-finance', '/facturation-electronique-amoa'],
        'guardrails' => 'Conserver les deux appellations lorsque les sources utilisent Advantage Finance et SIGMA.',
    ],
    [
        'name' => 'Proginov',
        'slug' => 'proginov',
        'aliases' => ['Proginov'],
        'editor' => 'Proginov',
        'family' => 'ERP / Finance / Paie',
        'proof_level' => 'Solution évaluée en AMOA',
        'publication' => 'Oui avec formulation « solution évaluée »',
        'wording' => 'OLING a étudié / évalué Proginov dans le cadre de missions d’AMOA ou de choix de solution.',
        'target_pages' => ['/business-apps/erp', '/si-finance'],
        'guardrails' => 'Ne pas présenter Proginov comme solution déployée chez Cap Créole sans preuve de sélection finale.',
    ],
    [
        'name' => 'Cegid',
        'slug' => 'cegid',
        'aliases' => ['Cegid', 'CEGID', 'Cegid Relation Bancaire'],
        'editor' => 'Cegid',
        'family' => 'ERP / Finance / Trésorerie',
        'proof_level' => 'Environnement client documenté + compétence déclarée',
        'publication' => 'Oui avec rattachement prudent',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant Cegid.',
        'target_pages' => ['/business-apps/erp', '/si-finance', '/amoa-si'],
        'guardrails' => 'Cegid et Sage X3 sont deux solutions distinctes. Ne jamais produire « Cegid X3 ».',
    ],
    [
        'name' => 'Dolibarr',
        'slug' => 'dolibarr',
        'aliases' => ['Dolibarr', 'Dolibarr ERP CRM'],
        'editor' => 'Communauté Dolibarr / DoliCloud selon hébergement',
        'family' => 'ERP / CRM',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Dolibarr lorsque la mission associée est documentée.',
        'target_pages' => ['/business-apps/erp', '/crm'],
        'guardrails' => 'Distinguer intégration/configuration réelle et simple facturation interne.',
    ],
    [
        'name' => 'Odoo',
        'slug' => 'odoo',
        'aliases' => ['Odoo', 'ODOO'],
        'editor' => 'Odoo',
        'family' => 'ERP / CRM',
        'proof_level' => 'AMOA / conception / échange projet',
        'publication' => 'Oui avec formulation « projet/solution abordé »',
        'wording' => 'OLING a abordé Odoo dans le cadre d’un cadrage / échange AMOA documenté.',
        'target_pages' => ['/business-apps/erp', '/crm'],
        'guardrails' => 'Ne pas transformer une phase de conception / avant-vente en référence client livrée.',
    ],
    [
        'name' => 'SAP S/4HANA',
        'slug' => 'sap-s4hana',
        'aliases' => ['SAP', 'SAP S/4HANA', 'S/4HANA'],
        'editor' => 'SAP',
        'family' => 'ERP / Finance',
        'proof_level' => 'Expérience / compétence équipe déclarée',
        'publication' => 'Oui en compétence générale',
        'wording' => 'Les équipes OLING disposent d’une expérience ou connaissance de SAP S/4HANA ; ne pas rattacher à un client sans preuve.',
        'target_pages' => ['/business-apps/erp', '/si-finance'],
        'guardrails' => 'Ne pas inventer de client ou de certification SAP.',
    ],
    [
        'name' => 'IFS',
        'slug' => 'ifs',
        'aliases' => ['IFS', 'IFS Cloud'],
        'editor' => 'IFS',
        'family' => 'ERP / EAM',
        'proof_level' => 'Expérience / compétence équipe déclarée',
        'publication' => 'Oui en compétence générale',
        'wording' => 'Les équipes OLING disposent d’une expérience ou connaissance de IFS ; ne pas rattacher à un client sans preuve.',
        'target_pages' => ['/business-apps/erp', '/gmao'],
        'guardrails' => 'Ne pas associer à un projet précis sans preuve.',
    ],
    [
        'name' => 'CIRIL Finance',
        'slug' => 'ciril-finance',
        'aliases' => ['CIRIL Finance', 'Ciril Finance'],
        'editor' => 'Ciril GROUP',
        'family' => 'Finance publique / GBCP',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant CIRIL Finance.',
        'target_pages' => ['/si-finance', '/amoa-si'],
        'guardrails' => 'Présenter comme application de l’écosystème analysé, sauf intervention spécifique démontrée.',
    ],
    [
        'name' => 'CIRIL RH',
        'slug' => 'ciril-rh',
        'aliases' => ['CIRIL RH', 'Ciril RH'],
        'editor' => 'Ciril GROUP',
        'family' => 'SIRH / Paie',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant CIRIL RH.',
        'target_pages' => ['/amoa-si'],
        'guardrails' => 'Écosystème analysé ; ne pas sur-vendre un rôle d’intégrateur.',
    ],
    [
        'name' => 'KELIO',
        'slug' => 'kelio',
        'aliases' => ['KELIO', 'Kelio'],
        'editor' => 'Bodet Software',
        'family' => 'SIRH / GTA',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant KELIO.',
        'target_pages' => ['/amoa-si'],
        'guardrails' => 'Utiliser comme environnement rencontré si le projet concerné est publié.',
    ],
    [
        'name' => 'MyReport',
        'slug' => 'myreport',
        'aliases' => ['MyReport', 'My Report'],
        'editor' => 'Report One',
        'family' => 'BI / Reporting',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant MyReport.',
        'target_pages' => ['/si-finance', '/facturation-electronique-amoa', '/amoa-si'],
        'guardrails' => 'Bon mot-clé de longue traîne sur SI Finance / RFE.',
    ],
    [
        'name' => 'EBP',
        'slug' => 'ebp',
        'aliases' => ['EBP', 'EBP Gestion Commerciale'],
        'editor' => 'EBP',
        'family' => 'Comptabilité / Gestion commerciale',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant EBP.',
        'target_pages' => ['/facturation-electronique-amoa', '/si-finance'],
        'guardrails' => 'Contextualiser dans les flux RFE et l’écosystème applicatif.',
    ],
    [
        'name' => 'Chorus Pro',
        'slug' => 'chorus-pro',
        'aliases' => ['Chorus Pro', 'ChorusPro'],
        'editor' => 'AIFE / État français',
        'family' => 'Facturation électronique / B2G',
        'proof_level' => 'Mission confirmée / environnement documenté',
        'publication' => 'Oui',
        'wording' => 'OLING intervient sur des projets impliquant Chorus Pro lorsque la mission associée est documentée.',
        'target_pages' => ['/facturation-electronique-amoa', '/si-finance'],
        'guardrails' => 'Plateforme publique, pas un progiciel privé ; conserver néanmoins dans la taxonomie outils.',
    ],
    [
        'name' => "So'Wave",
        'slug' => 'so-wave',
        'aliases' => ["So'Wave", 'So’Wave', 'SO WAVE'],
        'editor' => 'À confirmer',
        'family' => 'ERP métier / Eau / Interventions',
        'proof_level' => 'Mission confirmée',
        'publication' => 'Oui',
        'wording' => "OLING intervient sur des projets impliquant So'Wave lorsque la mission associée est documentée.",
        'target_pages' => ['/gmao', '/business-apps/erp'],
        'guardrails' => 'Conserver apostrophe canonique dans les contenus, slug sans apostrophe.',
    ],
    [
        'name' => 'wat.erp',
        'slug' => 'wat-erp',
        'aliases' => ['wat.erp', 'wat erp', 'WAT ERP'],
        'editor' => 'À confirmer',
        'family' => 'ERP métier / Eau',
        'proof_level' => 'Environnement client documenté',
        'publication' => 'Oui après validation du rattachement',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant wat.erp.',
        'target_pages' => ['/business-apps/erp', '/amoa-si'],
        'guardrails' => 'Rattachement client à confirmer avant citation nominative.',
    ],
    [
        'name' => 'IBM Maximo',
        'slug' => 'ibm-maximo',
        'aliases' => ['IBM Maximo', 'Maximo'],
        'editor' => 'IBM',
        'family' => 'GMAO / EAM',
        'proof_level' => 'Solution étudiée / benchmark AMOA GMAO',
        'publication' => 'Oui comme solution étudiée',
        'wording' => 'OLING a étudié / évalué IBM Maximo dans le cadre de missions d’AMOA ou de choix de solution.',
        'target_pages' => ['/gmao'],
        'guardrails' => 'Ne pas écrire « intégrateur IBM Maximo ».',
    ],
    [
        'name' => 'CARL Source',
        'slug' => 'carl-source',
        'aliases' => ['CARL Source', 'Carl Source'],
        'editor' => 'CARL Berger-Levrault',
        'family' => 'GMAO / EAM',
        'proof_level' => 'Solution étudiée / benchmark AMOA GMAO',
        'publication' => 'Oui comme solution étudiée',
        'wording' => 'OLING a étudié / évalué CARL Source dans le cadre de missions d’AMOA ou de choix de solution.',
        'target_pages' => ['/gmao'],
        'guardrails' => 'Formuler « solution analysée/évaluée » si aucun déploiement CARL n’est prouvé.',
    ],
    [
        'name' => 'Coswin 8i',
        'slug' => 'coswin-8i',
        'aliases' => ['Coswin 8i', 'Coswin'],
        'editor' => 'Siveco Group',
        'family' => 'GMAO / EAM',
        'proof_level' => 'Solution étudiée / benchmark AMOA GMAO',
        'publication' => 'Oui comme solution étudiée',
        'wording' => 'OLING a étudié / évalué Coswin 8i dans le cadre de missions d’AMOA ou de choix de solution.',
        'target_pages' => ['/gmao'],
        'guardrails' => 'Ne pas présenter comme intégration réalisée sans preuve.',
    ],
    [
        'name' => 'HxGN EAM',
        'slug' => 'hxgn-eam',
        'aliases' => ['HxGN EAM', 'Hexagon EAM'],
        'editor' => 'Hexagon',
        'family' => 'GMAO / EAM',
        'proof_level' => 'Solution étudiée / benchmark AMOA GMAO',
        'publication' => 'Oui comme solution étudiée',
        'wording' => 'OLING a étudié / évalué HxGN EAM dans le cadre de missions d’AMOA ou de choix de solution.',
        'target_pages' => ['/gmao'],
        'guardrails' => 'Ne pas prétendre à une certification éditeur.',
    ],
    [
        'name' => 'QGIS',
        'slug' => 'qgis',
        'aliases' => ['QGIS'],
        'editor' => 'Projet open source QGIS',
        'family' => 'SIG / Cartographie',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant QGIS.',
        'target_pages' => ['/gmao', '/amoa-si', '/projets'],
        'guardrails' => 'Ne rattacher à Routes de Guadeloupe que si QGIS est explicitement confirmé dans les données projet.',
    ],
    [
        'name' => 'Business Geo / Business Geografic',
        'slug' => 'business-geo',
        'aliases' => ['Business Geo', 'Business Geografic', 'GEO'],
        'editor' => 'Business Geografic / Ciril GROUP',
        'family' => 'SIG / Cartographie',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant Business Geo / Business Geografic.',
        'target_pages' => ['/gmao', '/amoa-si'],
        'guardrails' => 'Utiliser l’appellation source la plus récente après vérification.',
    ],
    [
        'name' => 'TOPKAPI',
        'slug' => 'topkapi',
        'aliases' => ['TOPKAPI', 'Topkapi'],
        'editor' => 'AREAL / à confirmer selon version',
        'family' => 'Supervision / SCADA',
        'proof_level' => 'Environnement SI client documenté',
        'publication' => 'Oui',
        'wording' => 'OLING a analysé ou piloté des projets dans des environnements intégrant TOPKAPI.',
        'target_pages' => ['/gmao', '/amoa-si'],
        'guardrails' => 'Présenter comme application technique interfacée/analysée.',
    ],
    [
        'name' => 'Maarch',
        'slug' => 'maarch',
        'aliases' => ['Maarch', 'Maarch Courrier'],
        'editor' => 'Maarch',
        'family' => 'GED / GEC / Dématérialisation',
        'proof_level' => 'Solution rencontrée / expertise projet',
        'publication' => 'Oui après rattachement explicite',
        'wording' => 'Les équipes OLING disposent d’une expérience ou connaissance de Maarch ; ne pas rattacher à un client sans preuve.',
        'target_pages' => ['/amoa-si', '/projets'],
        'guardrails' => 'Ne pas présenter Maarch comme solution retenue à Goyave sans preuve explicite.',
    ],
    [
        'name' => 'Alfresco',
        'slug' => 'alfresco',
        'aliases' => ['Alfresco', 'Alfresco Content Services'],
        'editor' => 'Hyland',
        'family' => 'GED / ECM',
        'proof_level' => 'Solution rencontrée / expertise projet',
        'publication' => 'Oui en compétence générale',
        'wording' => 'Les équipes OLING disposent d’une expérience ou connaissance de Alfresco ; ne pas rattacher à un client sans preuve.',
        'target_pages' => ['/amoa-si'],
        'guardrails' => 'Ne pas associer à un client sans rattachement documentaire.',
    ],
    [
        'name' => 'VIF',
        'slug' => 'vif',
        'aliases' => ['VIF', 'ERP VIF'],
        'editor' => 'VIF',
        'family' => 'ERP agroalimentaire / MES',
        'proof_level' => 'Déclaré par la direction OLING – rattachement à compléter',
        'publication' => 'Oui en compétence générale après validation éditoriale',
        'wording' => 'Les équipes OLING disposent d’une expérience ou connaissance de VIF ; ne pas rattacher à un client sans preuve.',
        'target_pages' => ['/business-apps/erp', '/amoa-si'],
        'guardrails' => 'Avant publication comme cas client, rattacher VIF à une mission/source.',
    ],
];
