<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpMKeEN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpMKeEN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPpMKeEN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPpMKeEN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPpMKeEN\App_KernelDevDebugContainer([
    'container.build_hash' => 'PpMKeEN',
    'container.build_id' => '4b8703d9',
    'container.build_time' => 1681690629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpMKeEN');
