<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mGRx6a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mGRx6a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1mGRx6a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1mGRx6a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1mGRx6a\App_KernelDevDebugContainer([
    'container.build_hash' => '1mGRx6a',
    'container.build_id' => 'a918c3b6',
    'container.build_time' => 1682123749,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1mGRx6a');
