<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeqN97x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeqN97x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeqN97x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXeqN97x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXeqN97x\App_KernelDevDebugContainer([
    'container.build_hash' => 'XeqN97x',
    'container.build_id' => 'fa30eb1c',
    'container.build_time' => 1681094039,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeqN97x');
